use spring1;
CREATE TABLE TBL_USER_ADMIN(
	id INT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(50) NOT NULL,
    cnpj CHAR(14) NOT NULL UNIQUE,
	telefone CHAR(12) UNIQUE,
    email VARCHAR(120) NOT NULL UNIQUE,
    senha VARCHAR(100) NOT NULL,
    verif_senha VARCHAR(100) NOT NULL
);
CREATE TABLE TBL_USER(
	id INT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(50) NOT NULL,
    cpf CHAR(14) NOT NULL UNIQUE,
    telefone CHAR(12) UNIQUE,
    email VARCHAR(120) NOT NULL UNIQUE,
    senha VARCHAR(100) NOT NULL,
    verif_senha VARCHAR(100) NOT NULL,
    foto_url VARCHAR(249) UNIQUE
);
CREATE TABLE TBL_SENSOR(
	id INT PRIMARY KEY AUTO_INCREMENT,
    num_serie INT NOT NULL UNIQUE,
    posicao VARCHAR(50) NOT NULL,
    sensor_status VARCHAR(50) NOT NULL,
    temperatura DECIMAL(4,2) NOT NULL
);
CREATE TABLE TBL_PRODUTO(
	id INT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(60) NOT NULL,
    descricao VARCHAR(300) NOT NULL,
    temp_max DECIMAL(4,2) NOT NULL,
    temp_min DECIMAL(4,2) NOT NULL,
    foto_url VARCHAR(249) UNIQUE
);
CREATE TABLE TBL_CARGA(
	id INT PRIMARY KEY AUTO_INCREMENT,
    codigo_produto INT,
    valor DECIMAL(6,2) NOT NULL
);
CREATE TABLE TBL_VEICULO(
	id INT PRIMARY KEY AUTO_INCREMENT,
    placa CHAR(7) UNIQUE NOT NULL,
    modelo VARCHAR(50) NOT NULL,
    volume FLOAT NOT NULL,
    motorista VARCHAR(60) NOT NULL,
    codigo_sensor INT
);
CREATE TABLE TBL_USO(
	id INT PRIMARY KEY AUTO_INCREMENT,
    dt DATETIME NOT NULL,
    descricao VARCHAR(300) NOT NULL,
    codigo_carga INT,
    codigo_veiculo INT
);
	